name: Facebook Auto Share (Manual Input)

on:
  workflow_dispatch:
jobs:
  get-input:
    runs-on: ubuntu-latest
    steps:
      - name: Prompt user
        id: input
        uses: boasihq/interactive-inputs@v2
        with:
          title: 'Enter FB details'
          interactive: |
            fields:
              - label: cookie
                type: text
                required: true
              - label: url
                type: text
                required: true
              - label: limit
                type: text
                required: true
      - name: Run script
        run: |
          python main.py "${{ steps.input.outputs.cookie }}" "${{ steps.input.outputs.url }}" "${{ steps.input.outputs.limit }}"
